### ISSUE TITLE
Delete master when downloading new

### ISSUE THREAD

**Issue by g-w1** [marler8997/zigup#3]
It would be nice if when doing `zigup master`, it would auto delete the previous day's master instead of just keeping it.

**Comment by marler8997** [comment]
I plan on creating a "clean" command (haven't done so yet).  This would clean all compilers except the current "default" compiler, and any compilers that have been "marked" to keep.

The issue with deleting the previous compiler is some people may want to roll back to the previous version, especially if something breaks on the latest version.  I think it's safer to keep the previous compiler, at least by default.  I wouldn't be opposed to a command-line option that automatically deletes the previous compiler.  Or maybe you have a better idea? Thoughts?

**Comment by g-w1** [comment]
I think that it would be beneficial to add a config file for multiple reasons. I forked zigup and am using the fork because I want my zig install dir to be in .local/zig and don't want to pass a cli flag every time. In the config file, users could also specify how many master versions they want, and the "keep" compilers. I am imagining it to look something like this:

```json
{
  "install_dir":"/home/user/.local/zig",
  "symlink_path":"/home/user/.local/bin/zig",
  "keep":["master", "0.5.0"],
  "master_number_to_keep": 2,
}
```

This could be somewhere like ~/.zigup.json and it would be pretty easy to parse because of std.json.

What do you think?

**Comment by marler8997** [comment]
I documented my thoughts on that here: https://github.com/marler8997/zigup#configuration

However, I like the "one way to do things" philosophy, and because there is a command-line parameter for this.  So you can already configure the install directory using a wrapper script where you always add the "--install-dir" to the command line.  Do you think we should also support a config file even though we already have a way to support this use case with a wrapper script?

**Comment by g-w1** [comment]
Oh. I was thinking that it would be better to remove the cli flags and put everything in the config file. I think that this is more consistent and is better than cli flagssince there are no default paths, but all user specified, and I especially think a config file is better for specifying which compilers to keep, rather than making a database based on cli flags. I haven't thought of making a wrapper script, but that is a good idea. What do you think?

**Comment by marler8997** [comment]
The reason I added the CLI flags is so that you could change these options on each invocation.   In other words, you can keep your options local to your process and not touch anyone elses process.  I think this tool should have that level of control, and this interface can be expanded to be system-wide through things like wrapper scripts.  The biggest argument for a config file that I can think of is it seems to be the more "obvious" solution.  The typical pattern is to use command-line arguments for temporary one time config, and a file for more permanent system-wide config.  The other benefit I can see is a wrapper script can be problematic because how do you find the real `zigup` in your wrapper script?  It can be done, but it might be a little complex.

Any more thoughts to add?

**Comment by g-w1** [comment]
I don't have any more thoughts. You should make the final decision.
Thanks

**Comment by marler8997** [comment]
I think the next step here is to implement the "clean" command.  Once that is done we'll have a bit more information on what to do next.

**Comment by g-w1** [comment]
Now with clean, closing.
